// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my_test.proto

#ifndef PROTOBUF_INCLUDED_my_5ftest_2eproto
#define PROTOBUF_INCLUDED_my_5ftest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_my_5ftest_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_my_5ftest_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_my_5ftest_2eproto();
namespace fuckingasshole {
class testwhat;
class testwhatDefaultTypeInternal;
extern testwhatDefaultTypeInternal _testwhat_default_instance_;
}  // namespace fuckingasshole
namespace google {
namespace protobuf {
template<> ::fuckingasshole::testwhat* Arena::CreateMaybeMessage<::fuckingasshole::testwhat>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace fuckingasshole {

// ===================================================================

class testwhat :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fuckingasshole.testwhat) */ {
 public:
  testwhat();
  virtual ~testwhat();

  testwhat(const testwhat& from);

  inline testwhat& operator=(const testwhat& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  testwhat(testwhat&& from) noexcept
    : testwhat() {
    *this = ::std::move(from);
  }

  inline testwhat& operator=(testwhat&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const testwhat& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const testwhat* internal_default_instance() {
    return reinterpret_cast<const testwhat*>(
               &_testwhat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(testwhat* other);
  friend void swap(testwhat& a, testwhat& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline testwhat* New() const final {
    return CreateMaybeMessage<testwhat>(nullptr);
  }

  testwhat* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<testwhat>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const testwhat& from);
  void MergeFrom(const testwhat& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(testwhat* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 opint = 1;
  bool has_opint() const;
  void clear_opint();
  static const int kOpintFieldNumber = 1;
  ::google::protobuf::int32 opint() const;
  void set_opint(::google::protobuf::int32 value);

  // optional bool opbl = 2;
  bool has_opbl() const;
  void clear_opbl();
  static const int kOpblFieldNumber = 2;
  bool opbl() const;
  void set_opbl(bool value);

  // @@protoc_insertion_point(class_scope:fuckingasshole.testwhat)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int32 opint_;
  bool opbl_;
  friend struct ::TableStruct_my_5ftest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// testwhat

// optional int32 opint = 1;
inline bool testwhat::has_opint() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void testwhat::clear_opint() {
  opint_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int32 testwhat::opint() const {
  // @@protoc_insertion_point(field_get:fuckingasshole.testwhat.opint)
  return opint_;
}
inline void testwhat::set_opint(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  opint_ = value;
  // @@protoc_insertion_point(field_set:fuckingasshole.testwhat.opint)
}

// optional bool opbl = 2;
inline bool testwhat::has_opbl() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void testwhat::clear_opbl() {
  opbl_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool testwhat::opbl() const {
  // @@protoc_insertion_point(field_get:fuckingasshole.testwhat.opbl)
  return opbl_;
}
inline void testwhat::set_opbl(bool value) {
  _has_bits_[0] |= 0x00000002u;
  opbl_ = value;
  // @@protoc_insertion_point(field_set:fuckingasshole.testwhat.opbl)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace fuckingasshole

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_my_5ftest_2eproto
